### ISSUE TITLE
Implement cookie function for password

### ISSUE THREAD

**Issue by jeppestaerk** [jeppestaerk/erderkage#22]

**Comment by Madsn** [comment]
TODO: Validate PW on server and generate token to be stored on client side

**Comment by jeppestaerk** [comment]
Maybe a copy past of this:
https://github.com/jeppestaerk/ITTWEB-Assignment4-FitnessApp/blob/master/server/models/user.js
https://github.com/jeppestaerk/ITTWEB-Assignment4-FitnessApp/blob/master/server/controllers/users.js
Then the api can be authenticate with middleware like this:
https://github.com/jeppestaerk/ITTWEB-Assignment4-FitnessApp/blob/50947379efe625e436b992601ce81b18e50fdc43/server/router.js#L9

**Comment by jeppestaerk** [comment]
Is this a closed issue @Madsn ?
